name: Run Tests

on:
  push:
    branches: [ main, develop, deploy ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        uv pip install --system -e .
    
    - name: Run tests
      run: |
        pytest -v --tb=short
    
    - name: Generate coverage report (optional)
      run: |
        uv pip install --system pytest-cov
        pytest --cov=. --cov-report=xml
    
    - name: Upload coverage (optional)
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: false